name: Test
on: [push]
env:
  FLEEK_API_KEY: ${{ secrets.FLEEK_API_KEY }}
  FLEEK_API_SECRET: ${{ secrets.FLEEK_API_SECRET }}
  INFURA_PROJECT_ID: ${{ secrets.INFURA_PROJECT_ID }}
  INFURA_PROJECT_SECRET: ${{ secrets.INFURA_PROJECT_SECRET }}
  PINATA_API_KEY: ${{ secrets.PINATA_API_KEY }}
  PINATA_API_SECRET: ${{ secrets.PINATA_API_SECRET }}
  WEB3STORAGE_API_TOKEN: ${{ secrets.WEB3STORAGE_API_TOKEN }}
  EVER_API_KEY: ${{ secrets.EVER_API_KEY }}
  EVER_API_SECRET: ${{ secrets.EVER_API_SECRET }}
  EVER_BUCKET_NAME: ${{ secrets.EVER_BUCKET_NAME }}
jobs:
  test:
    uses: snapshot-labs/actions/.github/workflows/test.yml@main
    secrets: inherit
